version: "3.9"

services:
  app:
    build: .
    container_name: php_quotes_api
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: quotesdb
      DB_USER: postgres
      DB_PASS: postgres

  db:
    image: postgres:16
    container_name: quotes_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: quotesdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: